# Generated by Django 4.2.6 on 2023-10-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=10),
            preserve_default=False,
        ),
    ]
