# Generated by Django 4.2.6 on 2023-10-26 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_genero_alter_movie_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
