# Generated by Django 4.2.6 on 2023-10-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fecha_estreno',
            field=models.DateField(default='1500-05-10'),
        ),
    ]
